122 add multiple incomes expenses
tudorgrig/my-money-tracker pull request #132
Opened 2017-03-18 23:02 UTC by florinIacob

2017-03-20 09:59 UTC, tudorgrig requested changes

2017-03-20 09:59 UTC, tudorgrig commented on src/main/java/com/TheAccountant/controller/ExpenseController.java
> +                    if (category == null) {
This whole for block needs to be shorter and much clearer. 
Move the setting of the category in a new method so that in this block I just see expense.setCategory(resolveCategory(..));

2017-03-20 09:59 UTC, tudorgrig commented on src/main/java/com/TheAccountant/controller/ExpenseController.java
> +                        throw new BadRequestException("Wrong currency code for index [" + index + "]!");
This message should include the code that is wrong also

2017-03-20 09:59 UTC, tudorgrig commented on src/main/java/com/TheAccountant/controller/ExpenseController.java
> +                for (Expense expense : expenses) {
use Java8 streams instead of for.
expenses.stream().map(expense -> persistExpenseData()).collect(toList());

2017-03-20 09:59 UTC, tudorgrig commented on src/main/java/com/TheAccountant/controller/ExpenseController.java
> +                return new ResponseEntity<>(createdExpensesDTO, HttpStatus.OK);
return list instead of array

2017-04-03 21:50 UTC, florinIacob commented on src/main/java/com/TheAccountant/controller/ExpenseController.java
> +                for (Expense expense : expenses) {
Cannot use stream() for Expense[] array.

2017-04-10 05:23 UTC, merged